name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Laravel Optimization & Cache
      run: |
        php artisan config:clear
        php artisan route:clear
        composer install --optimize-autoloader --no-dev
        php artisan config:cache
        php artisan route:cache

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

    - name: Prepare deployment zip for Elastic Beanstalk
      run: |
        mkdir -p .ebextensions
        echo 'files:
  "/etc/httpd/conf.d/00_application.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      DocumentRoot /var/app/current/public

      <Directory /var/app/current/public>
        AllowOverride All
        Require all granted
      </Directory>' > .ebextensions/00_document_root.config

        zip -r deploy-package.zip . -x '*.git*' 'tests/*' 'database/*.sqlite'

    # Optional: Deploy to Elastic Beanstalk using AWS CLI
    # Uncomment the block below and set secrets in GitHub repo settings

    # - name: Deploy to Elastic Beanstalk
    #   uses: einaregilsson/beanstalk-deploy@v21
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     application_name: laravel
    #     environment_name: Laravel-env
    #     region: ap-southeast-1
    #     version_label: github-${{ github.run_number }}
    #     deployment_package: deploy-package.zip
